/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerCustomization {
  'unlockedIcons' : Array<string>,
  'selectedColor' : string,
  'selectedIcon' : string,
  'unlockedColors' : Array<string>,
}
export interface PlayerData {
  'progress' : PlayerProgress,
  'customization' : PlayerCustomization,
}
export interface PlayerProgress {
  'bestProgress' : Array<[bigint, bigint]>,
  'levelsCompleted' : Array<bigint>,
  'levelAttempts' : Array<[bigint, bigint]>,
}
export interface _SERVICE {
  'completeLevel' : ActorMethod<[bigint], undefined>,
  'getPlayerData' : ActorMethod<[], [] | [PlayerData]>,
  'initializePlayer' : ActorMethod<[], undefined>,
  'recordLevelAttempt' : ActorMethod<[bigint], undefined>,
  'selectColor' : ActorMethod<[string], undefined>,
  'selectIcon' : ActorMethod<[string], undefined>,
  'updateBestProgress' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];