/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerProgress = IDL.Record({
  'bestProgress' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'levelsCompleted' : IDL.Vec(IDL.Nat),
  'levelAttempts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const PlayerCustomization = IDL.Record({
  'unlockedIcons' : IDL.Vec(IDL.Text),
  'selectedColor' : IDL.Text,
  'selectedIcon' : IDL.Text,
  'unlockedColors' : IDL.Vec(IDL.Text),
});
export const PlayerData = IDL.Record({
  'progress' : PlayerProgress,
  'customization' : PlayerCustomization,
});

export const idlService = IDL.Service({
  'completeLevel' : IDL.Func([IDL.Nat], [], []),
  'getPlayerData' : IDL.Func([], [IDL.Opt(PlayerData)], ['query']),
  'initializePlayer' : IDL.Func([], [], []),
  'recordLevelAttempt' : IDL.Func([IDL.Nat], [], []),
  'selectColor' : IDL.Func([IDL.Text], [], []),
  'selectIcon' : IDL.Func([IDL.Text], [], []),
  'updateBestProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerProgress = IDL.Record({
    'bestProgress' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'levelsCompleted' : IDL.Vec(IDL.Nat),
    'levelAttempts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const PlayerCustomization = IDL.Record({
    'unlockedIcons' : IDL.Vec(IDL.Text),
    'selectedColor' : IDL.Text,
    'selectedIcon' : IDL.Text,
    'unlockedColors' : IDL.Vec(IDL.Text),
  });
  const PlayerData = IDL.Record({
    'progress' : PlayerProgress,
    'customization' : PlayerCustomization,
  });
  
  return IDL.Service({
    'completeLevel' : IDL.Func([IDL.Nat], [], []),
    'getPlayerData' : IDL.Func([], [IDL.Opt(PlayerData)], ['query']),
    'initializePlayer' : IDL.Func([], [], []),
    'recordLevelAttempt' : IDL.Func([IDL.Nat], [], []),
    'selectColor' : IDL.Func([IDL.Text], [], []),
    'selectIcon' : IDL.Func([IDL.Text], [], []),
    'updateBestProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };